version: '3'
services:
  consul-agent-1: &consul-agent
    image: consul:latest
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"
    volumes:
      - ../data/consul_agent_1:/consul/data
  consul-agent-2:
    <<: *consul-agent
    volumes:
      - ../data/consul_agent_2:/consul/data
  consul-agent-3:
    <<: *consul-agent
    volumes:
      - ../data/consul_agent_3:/consul/data
  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
    volumes:
      - ../data/consul_server_1:/consul/data
  consul-server-2:
    <<: *consul-server
    volumes:
      - ../data/consul_server_2:/consul/data
  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"
    volumes:
      - ../data/consul_server_3:/consul/data